-- 코드를 입력하세요
-- 환자 정보를 담은 PATIENT 테이블
-- 의사 정보를 담은 DOCTOR 테이블
-- 진료 예약목록을 담은 APPOINTMENT에 대한 테이블
-- APNT_YMD = 2022년 4월 13일
-- APNT_CNCL_YN = N
-- MCDP_CD = CS
SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM PATIENT P
INNER JOIN APPOINTMENT A
ON P.PT_NO = A.PT_NO
INNER JOIN DOCTOR D
ON A.MDDR_ID = D.DR_ID
WHERE TO_CHAR(A.APNT_YMD, 'YYYYMMDD') = '20220413'
AND A.APNT_CNCL_YN = 'N'
AND A.MCDP_CD = 'CS'
ORDER BY A.APNT_YMD