-- 코드를 입력하세요
WITH DONE AS 
(SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
 FROM USED_GOODS_BOARD
 WHERE STATUS = 'DONE'
 GROUP BY WRITER_ID
 HAVING SUM(PRICE) >= 700000)

SELECT U.USER_ID, U.NICKNAME, D.TOTAL_SALES
FROM DONE D
JOIN USED_GOODS_USER U
ON D.WRITER_ID = U.USER_ID
ORDER BY D.TOTAL_SALES;