-- 코드를 입력하세요
SELECT RH.CAR_ID AS CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
ON C.CAR_ID = RH.CAR_ID
WHERE CAR_TYPE = '세단'
AND TO_CHAR(RH.START_DATE, 'YYYYMM') = '202210'
GROUP BY RH.CAR_ID
ORDER BY RH.CAR_ID DESC;