-- 코드를 입력하세요
-- 2022년 5월 조건
-- 진료과코드(MCDP_CD) 별로.. -> group by
SELECT MCDP_CD AS "진료과코드", COUNT(APNT_NO) AS "5월예약건수"
FROM APPOINTMENT
WHERE TO_CHAR(APNT_YMD, 'YYYY-MM') = '2022-05'
GROUP BY MCDP_CD
ORDER BY COUNT(APNT_NO), MCDP_CD